config/routes.rb
IdssSe::Application.routes.draw do
  get "jobs/index"

  get "about_us/index"

  get "contacts/index"

  get "contacs/index"

  get "what_we_do/index"

  get "referenses/index"

  get "home/index"
  resources :referenses, :what_we_do, :contacts, :about_us, :jobs

  get '/vara-tjanster' => "what_we_do#index", as: :what_we_do
  get '/om-oss' => "about_us#index", as: :about_us
  get '/kontakta-oss' => "contacts#index", as: :contacts
  get '/jobba-hos-oss' => "jobs#index", as: :jobs
  post '/kontakta-oss' => "contacts#create", as: :contacts
  match "/referenser/:referens/" => "referenses#show", as: :referens

  root :to => 'home#index'

end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  	
  end
  def create
  	if request.post?
  		 ContactMailer.contact_email(params[:contact]).deliver
  		 redirect_to :back
  	end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
  end
end

app/controllers/referenses_controller.rb
class ReferensesController < ApplicationController
  def index
  end
  def show
  	
  end
end

app/controllers/what_we_do_controller.rb
class WhatWeDoController < ApplicationController
  def index
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacs_helper.rb
module ContacsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/referenses_helper.rb
module ReferensesHelper
end

app/helpers/what_we_do_helper.rb
module WhatWeDoHelper
end

app/views/about_us/index.html.erb
<div class="row">
	<div id="content" class="container">
    <div id="big_text" class="span12">
          <h1 class="grey"><span class="big">Vi är <span class="black">idss</span> en webbyrå i småland!</h1>
          <p class="large">Vi är ett glatt gäng som jobbar några mil utanför Växjö. Eftersom vi ligger i småland försöker vi alltid hålla "smålänska priser".</p>
          <p class="large">Vår vision är att alltid leverera unika hemsidor till kunden, vi använder aldrig några klara mallar när vi tar fram en hemsida till kunden då vi anser att slut resultatet blir bättre om man skräddarsyr hemsidan för just den kund man jobbar med.</p>
          <p class="large black"><b>Välkommen till en annorlunda webbyrå!</p>
    </div> 
        
	</div>
</div>
</div> <!-- END CONTAINER IN APPLICATION -->
<div style="text-align: center;" id="content_under">
  <div style="margin-top: 0px;" class="container">
   <div style="margin-left: 80px;" id="description" class="span12">
   	<div class="span5">
		<h2 class="black">Företagsfakta</h2>
		<p class="large">International Domain Store Sweden AB</p>
		<p class="large">Org nr: 556806-6897</p>
	</div>
  <div class="span5">
    <h2 class="black">Kontaktinformation</h2>
   <p class="large">idss-design.se</p>

<p class="large">info@idss-design.se</p>

<p class="large">Direkt: 0470-12010</p>
  </div>
	</div>
    <div id="push"></div>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="row">
	<div id="content" class="container">
     <div id="big_text" class="span12">
          <h1 class="grey"><span class="big"><span class="black">Kontakta oss</span> så kan vi hjälpa dig</h1>
          <p class="large">Internet: idss-design.se</p>
          <p class="large">Email: info@idss-design.se</p>
          <p class="large">Direkt: 0470-12010</p>
          <p class="large black">...eller fyll i formuläret nedan så hör vi av oss.</p>
          <i style="font-size: 50px;" class="icon-arrow-down black"></i>
    </div> 
        </div>
</div>
</div> <!-- END CONTAINER IN APPLICATION -->
<div style="text-align: center;" id="content_under">
  <div style="margin-top: 30px;" class="container">
   <div style="margin-left: 43px;" id="description" class="span12">
	<%= form_tag contacts_path do %>
		<%= text_field_tag "contact[name]", nil,  class: "big", placeholder: "Namn", required: true %><br/>
		<%= text_field_tag "contact[email]", nil,  class: "big", placeholder: "E-postadress", required: true %><br/>
		<%= text_area_tag  "contact[message]", nil,  class: "big", placeholder: "Meddelande" %><br/>
		<%= submit_tag  "Skicka", class: "btn" %><br/>
	<% end %>
	</div>
    <div id="push"></div>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
		<div id="content" class="container">
          <div id="hero">

            <div class="flexislider span12">
              <ul class="slides">
              	<!--   <li style=""><%= link_to (image_tag "hero1.png"), referens_path("ana") %></li>
                <li><%= link_to (image_tag "hero2.png"), contacts_path %></li> -->
           		<li style="">
					<div class="hero-item">
						<h1 class="normal uppercase">ANA BEDDING AB </h1>
						<p><%= link_to "www.ana.se", "http://www.ana.se" %></p>
						<p>Idss fick i uppdrag att utveckla en helt ny unik design till ana beddings nya hemsida. Vi bytte också hela plattformen och resultatet blir en levande hemsida med många olika färger.</p>
						<p><%= link_to "Läs mer om ana här", referens_path("ana") %></p>
					</div>
					<%= link_to (image_tag "hero1.png"), referens_path("ana") %>
				</li>
				<li style="">
					<div class="hero-item">
						<h1 class="normal uppercase">ANAHOTELL</h1>
						<p><%= link_to "www.anahotell.se", "http://www.hotellsängar.se" %></p>
						<p>Eftersom ana blev så nöjda med hemsidan fick vi också göras deras hotellhemsida. Sidan är helt responsiv.</p>
						<p><%= link_to "Läs mer om anahotell här", referens_path("anahotell") %></p>
					</div>
					<%= link_to (image_tag "anahotell.png"), referens_path("anahotell") %>
				</li>
				<li style="">
					<div class="hero-item">
						<h1 class="normal uppercase">Domainstore</h1>
						<p><%= link_to "www.domainstore.se", "http://www.domainstore.se" %></p>
						<p>Idss fick i uppdrag att utveckla en auktionsida för domainstore.se. Kunderna ska kunna lägga bud på domäner och den som har sista budet vinner således domänen.</p>
						<p><%= link_to "Läs mer om domainstore.se här", referens_path("domainstore") %></p>
					</div>
					<%= link_to (image_tag "hero3.png"), referens_path("domainstore") %>
				</li>
              </ul>
            </div>
          </div>
			<div id="push"></div>
		</div>
</div>
</div> <!-- END CONTAINER IN APPLICATION -->
<div id="content_under">
  <div class="container">
   <div id="description" class="span12">
	
	<div class="fmcircle_out">
			<%= link_to what_we_do_path do %>
				<div class="fmcircle_border">
					<div class="fmcircle_in fmcircle_dark">
						<span>Design</span><img src="https://dl.dropbox.com/u/65958930/uploads/cssdeck/design.png" alt="" />
					</div>
				</div>
			<% end %>
	</div>
	<div class="fmcircle_out">
			<%= link_to what_we_do_path do %>
				<div class="fmcircle_border">
					<div class="fmcircle_in fmcircle_dark">
						<span>Utveckling</span><img src="https://dl.dropbox.com/u/65958930/uploads/cssdeck/develop.png" alt="" />
					</div>
				</div>
			<% end %>
	</div>
	<div class="fmcircle_out">
			<%= link_to about_us_path do %>
				<div class="fmcircle_border">
					<div class="fmcircle_in fmcircle_dark">
						<span>Byrån</span><img src="https://dl.dropbox.com/u/65958930/uploads/cssdeck/develop.png" alt="" />
					</div>
				</div>
			<% end %>
	</div>
	</div>
    <div id="push"></div>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="row">
	<div style="min-height: 300px;" id="content" class="container">
    <h1 class="normal">Lediga jobb</h1>
    <p>Jus nu har vi inga lediga jobb, men du kan ändå skicka in ett CV och personlig brev till oss på <b>jobb@idss-design.se</b> så kommer vi titta igenom det.</p>
     </div>
</div>
</div> <!-- END CONTAINER IN APPLICATION -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<!-- Rean's note: if you're wondering what are these items below, you should follow the link below -->
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->  <!--<![endif]-->

  <!-- Set the viewport width to device width for mobile -->


  <!-- Included CSS Files -->

  <!--[if lt IE 9]>
          <link rel="stylesheet" href="stylesheets/ie.css">
  <![endif]--><script type="text/javascript" src="javascripts/modernizr.foundation.js"></script>

  <!-- IE Fix for HTML5 Tags -->
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

 <%= display_meta_tags :site => 'IDSS - En webbyrå i småland' %>
 <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap.min.css" rel="stylesheet">
  <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet"> -->
  <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>

  
  <%= javascript_include_tag "application" %>
  <script src="http://yandex.st/highlightjs/6.1/highlight.min.js"></script>
  <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.0/js/bootstrap.min.js"></script>
  <%= favicon_link_tag '/idss.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div style="display: none;" id="overlay">
  <div class="container">
  <div class="" style="position: relative; top: 300px; margin-left: 0px;"> 
    <h2 class="brand">idss-design.se <%= image_tag("359.gif",width: "50") %> </h2>
  </div>
</div>
</div>
<div class="container">
	<div class="row">
		<div id="brand" class="span4"><%= link_to (image_tag("logo.png")), root_path  %> <div id="home" style="display: none; margin-top: -70px; margin-left: 180px; position:relative;"><i style="font-size: 30px; color: black;" class="icon-home"></i></div></div>
		<div id="menu" class="ph-dot-nav nav">
			<%= active_link_to "HEM", root_path %>
      <%= active_link_to "OM IDSS", about_us_path %>
      <%= active_link_to "VÅRA TJÄNSTER", what_we_do_path %>
      <%= active_link_to "KONTAKT", contacts_path %>
    <div class="effect"></div>
		</div>
	</div>
	
 <%= yield %>
<div id="footer">
  <div class="container">

    <p class="muted credit">
      <div id="buisness" class="span2">
        <h4 class="footer">Kontakt</h4>
        <p>idss-design.se</p>
        <p>info@idss-design.se</p>
        <p>Direkt: 0470-12010</p>
        <!-- <dichrv class="ringMenu">
          <ul>
            <li class="main">
              <a href="#main">
                <%=image_tag "/assets/icons/heart.png" %></a>
            </li>
            <li class="top">
              <a href="#top">
                <%=image_tag "/assets/icons/twitter.png" %></a>
            </li>
            <li class="right">
              <a href="#right">
                <%=image_tag "/assets/icons/facebook.png" %></a>
            </li>
            <li class="bottom">
              <a href="#bottom">
                <%=image_tag "/assets/icons/gplus.png" %></a>
            </li>
            <li class="left">
              <a href="#left">
                <%=image_tag "/assets/icons/linkedin.png" %></a>
            </li>
          </ul>
          </dichrv> -->
          <!-- /.ringMenu --> 
        </div>
        <div style="line-height: 10px;" class="span2 offset1">
        <h4 class="footer">Byrån</h4>
        <p><%= active_link_to "Nya jobb", jobs_path %></p>
        <p><%= active_link_to "kontakta oss", contacts_path %></p>
        
        </div>
        <div style="line-height: 10px;" class="span4 offset1">
        <h4 class="footer">Socialt</h4>
        <div id="socials">
          <div class="icons"><%= link_to (image_tag "/assets/icons/facebook.png"), "https://www.facebook.com/IdssDesign" %></div>
          <div class="icons"><%= image_tag "/assets/icons/twitter.png" %></div>
        </div>
        </div>
        <!-- <div class="seperatorTop"></div>
        <div class="seperatorBottom"></div> -->
      </p>
    </div>
  </div>
        	


</body>

</html>

app/views/referenses/index.html.erb
<h1>Några av de lösningar vi gjort åt kunder</h1>
<div class="img_wrapper span12">
	<div class="item span5"><img src="/assets/ana.png">
		<!-- <div class="ref-text">dsadsd</div> -->
	</div>
	<div class="item span5"><img src="/assets/ana.png">
	</div>
	<div class="item span5"><img src="/assets/ana.png">
	</div>
	<div class="item span5"><img src="/assets/ana.png">
	</div>
	<div class="item span5"><img src="/assets/ana.png">
	</div>

</div>


<script>
// On window load. This waits until images have loaded which is essential
  $(window).load(function(){
    
    // Fade in images so there isn't a color "pop" document load and then on window load
    $(".item img").fadeIn(500);
    
    // clone image
    $('.item img').each(function(){
      var el = $(this);
      el.css({"position":"absolute"}).wrap("<div class='img_wrapper' style='display: inline-block'>").clone().addClass('img_grayscale').css({"position":"absolute","z-index":"998","opacity":"0"}).insertBefore(el).queue(function(){
        var el = $(this);
        el.parent().css({"width":this.width,"height":this.height});
        el.dequeue();
      });
      this.src = grayscale(this.src);
    });
    
    // Fade image 
    $('.item img').mouseover(function(){
      $(this).parent().find('img:first').stop().animate({opacity:1}, 1000);
    })
    $('.img_grayscale').mouseout(function(){
      $(this).stop().animate({opacity:0}, 1000);
    });   
  });
  
  // Grayscale w canvas method
  function grayscale(src){
    var canvas = document.createElement('canvas');
    var ctx = canvas.getContext('2d');
    var imgObj = new Image();
    imgObj.src = src;
    canvas.width = imgObj.width;
    canvas.height = imgObj.height; 
    ctx.drawImage(imgObj, 0, 0); 
    var imgPixels = ctx.getImageData(0, 0, canvas.width, canvas.height);
    for(var y = 0; y < imgPixels.height; y++){
      for(var x = 0; x < imgPixels.width; x++){
        var i = (y * 4) * imgPixels.width + x * 4;
        var avg = (imgPixels.data[i] + imgPixels.data[i + 1] + imgPixels.data[i + 2]) / 3;
        imgPixels.data[i] = avg; 
        imgPixels.data[i + 1] = avg; 
        imgPixels.data[i + 2] = avg;
      }
    }
    ctx.putImageData(imgPixels, 0, 0, 0, 0, imgPixels.width, imgPixels.height);
    return canvas.toDataURL();
    }

</script>

app/views/referenses/show.html.erb
<div class="row">
	<% if params[:referens] == "ana" %>
	<div id="content" class="container">
        <div class="span12">
        	<h1 style="text-align:center;" class="tlt">ANA BEDDING AB</h1>
        </div> 
        <div class="span8 offset2"><%= image_tag("ana.png") %></div>
	</div>
	<% elsif params[:referens] == "domainstore" %>
	<div id="content" class="container">
        <div class="span12">
        	<h1 style="text-align:center;" class="tlt">DOMAINSTORE.SE</h1>
        </div> 
        <div class="span8 offset2"><%= image_tag("domainstore.png") %></div>
	</div>
	<% elsif params[:referens] == "anahotell" %>
	<div id="content" class="container">
        <div class="span12">
        	<h1 style="text-align:center;" class="tlt">ANAHOTELL.SE</h1>
        </div> 
        <div class="span8 offset2"><%= image_tag("anahotell_referens.png") %></div>
	</div>
	<% end %>
</div>
</div> <!-- END CONTAINER IN APPLICATION -->
<div  id="content_under">
  <div  style="margin-top: 30px; margin-left: 160px;" class="container">
   <div id="description" class="span12">
	<% if params[:referens] == "ana" %>
	<div class="span3">
		<p><i class="icon-ok"></i> Unik design</p>
		<p><i class="icon-ok"></i> Produktkatalog</p>
		<p><i class="icon-ok"></i> Uppdateringsverktyg</p>
		<p><i class="icon-ok"></i> Webbshop</p>
		<p><i class="icon-ok"></i> Betalningslösning</p>
		<p><i class="icon-ok"></i> Mina sidor</p>
		<p><i class="icon-ok"></i> HTML 5 och CSS3</p>
		<p><i class="icon-ok"></i> Bildredigering</p>
	</div>
	<div class="span4">
		<p>ANA BEDDIGN AB är ett sängföretag i småland som tillverkar egna sängar.</p>
		<p>Vi fick i uppdrag att skapa en helt ny plattform och en helt ny unik design.</p>
        <p><i class="icon-chevron-right"></i> <%= link_to "Till hemsidan", "http://www.ana.se" %></p>
	</div>
	<div class="span4">
		<blockquote>
		  <p>Utvecklare Joakim kommenterar</p>
		  <small>ANA BEDDING var mycket roligt att jobba med. Eftersom dom har så mycket artiklar och olika komponenter så var det en utmaning att få allt på plats men i slutändan är vi mycket nöjda med allt ifrån design till plattform. </small>
		</blockquote>
	</div>
	<% elsif params[:referens] == "domainstore" %>
	<div class="span3">
		<p><i class="icon-ok"></i> Unik design</p>
		<p><i class="icon-ok"></i> Produktkatalog</p>
		<p><i class="icon-ok"></i> Uppdateringsverktyg</p>
		<p><i class="icon-ok"></i> Bakgrundsjobb</p>
		<p><i class="icon-ok"></i> Betalningslösning</p>
		<p><i class="icon-ok"></i> Kundsidor</p>
		<p><i class="icon-ok"></i> HTML 5 och CSS3</p>
	</div>
	<div class="span4">
		<p>domainstore.se är en auktionsida som auktionerar ut domäner till ett bra pris.</p>
        <p><i class="icon-chevron-right"></i> <%= link_to "Till hemsidan", "http://www.domainstore.se" %></p>
	</div>
	<div class="span4">
		<blockquote>
		  <p>Utvecklare Joakim kommenterar</p>
		   <small>Mycket roligt projekt att jobba med, byggt med ruby on rails för absolut bästa stabilitet.</small>
		</blockquote>
	</div>
	<% elsif params[:referens] == "anahotell" %>
	<div class="span3">
		<p><i class="icon-ok"></i> Unik design</p>
		<p><i class="icon-ok"></i> Responsiv design</p>
		<p><i class="icon-ok"></i> Uppdateringsverktyg</p>
		<p><i class="icon-ok"></i> HTML 5 och CSS3</p>
	</div>
	<div class="span4">
		<p>anahotell.se säljer hotellsängar till hotellkunder.</p>
        <p><i class="icon-chevron-right"></i> <%= link_to "Till hemsidan", "http://www.anahotell.se" %></p>
	</div>
	<div class="span4">
		<blockquote>
		  <p>Utvecklare Joakim kommenterar</p>
		   <small>Eftersom vi gjorde ana.se fick vi också i uppgift att göra anahotell.se. Sidan är helt responsiv.</small>
		</blockquote>
	</div>
	<% end %>
	</div>
    <div id="push"></div>
  </div>
</div>

app/views/what_we_do/index.html.erb
<div class="row">
	<div id="content" class="container">
        <div id="big_text" class="span12">
        	<h1 class="grey"><span class="big"><span class="black">idss</span> är en webbyrå, vi gör <span class="black">hemsidor</span>, design och allt därtill</span></h1>
        	<p class="large">Vi gör unika helhetslösningar och applikationer till små och stora företag.</p>
        </div> 
        
	</div>
</div>
</div> <!-- END CONTAINER IN APPLICATION -->
<div id="content_under">
  <div style="margin-top: 20px;" class="container">
   <div style="margin-left: 93px;" id="description" class="span12">
   	<div style="text-align: center;" class="span3">
   		<h2 >Webbutveckling</h2>
		<i style="font-size: 100px;" class="icon-desktop"></i>
		<p>Vi skapar hemsidor helt skräddarsydda för kundens behov.</p>
	</div>
	<div style="text-align: center;" class="span4">
   		<h2 >Responsiv webbdesign</h2>
		<i style="font-size: 100px;" class="icon-tablet"></i>
		<p>Innebär att layouten att förändras beroende på vilken skärmupplösning besökaren har. Då mer och mer kunder använder sina smartphones för att besöka hemsidor är detta en viktigt del i framtidens webbutveckling.</p>
	</div>
	<div style="text-align: center;" class="span3">
   		<h2>webbaplikationer</h2>
		<i style="font-size: 100px;" class="icon-cogs"></i>
		<p>Vi gör även webbaplikation. Så som ehandelslösningar.</p>
	</div>
	
	</div>
    <div id="push"></div>
  </div>
</div>